<?php
$config = array(
	'base_url' => site_url().'dashboard',
	'full_tag_open' => '<div class="pagination"><ul>',
	'full_tag_close' => '</ul></div>',
	'num_tag_open' => '<li>',
	'num_tag_close' => '</li>',
	'cur_tag_open' => '<li class="active"><a href="javascript:void()">',
	'cur_tag_close' => '</a></li>',
	'first_link' => '<<',
	'first_tag_open' => '<li>',
	'first_tag_close' => '</li>',
	'last_link' => '>>',
	'last_tag_open' => '<li>',
	'last_tag_close' => '</li>',
	'next_link' => 'Next &rarr;',
	'next_tag_open' => '<li class="next">',
	'next_tag_close' => '</li>',
	'prev_link' => '&larr; Previous',
	'prev_tag_open' => '<li class="prev">',
	'prev_tag_close' => '</li>',
);
